dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- pip install pyserial
- pip install pyflakes
- pip install pydiatra
- $if_pygments pip install docutils pygments
script:
- ./huawei-modem-status --help
- python3 -m pyflakes huawei-modem-status
- python3 -m pydiatra huawei-modem-status
- $if_pygments private/check-rst

# vim:ts=2 sts=2 sw=2 et
